export { default as DeadditBlackLogomark } from './DeadditBlackLogomark'
export { default as DeadditBlueLogomark } from './DeadditBlueLogomark'
export { default as DeadditMultiLockup } from './DeadditMultiLockup'
export { default as DeadditMultiLogomark } from './DeadditMultiLogomark'
export { default as DeadditRedLogomark } from './DeadditRedLogomark'